### ISSUE TITLE
Pip upload

### ISSUE THREAD

**Issue by alejandrogallo** [mfherbst/look4bas#2]
Great project.
What about writing a setup.py script in order to upload the whole thing to PyPi?

In principle I/you could take the following as a template
https://github.com/papis/papis/blob/master/setup.py

and this script to upload to pypi
https://github.com/papis/papis/blob/master/tools/update-pypi.sh

**Comment by mfherbst** [comment]
Good idea. Thanks for the suggestion. I'll get to it.
